ruby-rails/config/routes.rb
Cloud::Application.routes.draw do


  get "home/index"


  get "dashboard/index"


  devise_for :cloud_users

  
  resources :cloud_user do 
    put 'upgrade', :on => :member
    put 'downgrade', :on => :member
    get 'history', :on => :member
  end
  

  resources :instances do
    get 'history', :on => :collection
    get 'recent', :on => :collection
  end

  resources :virtual_interface_cloud_user_associations 


  resources :user_cloud_user_associations


  resources :user_project_associations


  resources :user_role_associations


  resources :user_project_role_associations


  resources :security_group_instance_associations 


  resources :projects


  resources :users


  resource :user_project_associations


  resources :virtual_interfaces 


  resources :snapshots


  resources :services


  resources :security_groups


  resources :security_group_rules


  resources :s3_images


  resources :networks


  resources :key_pairs


  resources :instance_types


  resources :instance_info_caches


  resources :floating_ips do
    get 'unassigned', :on => :collection
    get 'autoassigned', :on => :collection
  end


  resources :fixed_ips do
    get 'unassigned', :on => :collection
    get 'leased', :on => :collection
    get 'released', :on => :collection
  end


  resources :compute_nodes


  resources :certificates


  resources :image_properties

  
  root :to => 'home#index'


end

ruby-rails/app/models/fixed_ip.rb
class FixedIp < Nova
  attr_accessible :address, :allocated, :created_at, :deleted, :deleted_at, :host, :instance_id, :leased, :network_id, :reserved, :updated_at, :virtual_interface_id

  scope :fixed_active, where("allocated=?", 1)
  scope :fixed_inactive, where("allocated=?", 0)

  has_one :virtual_interface
  has_many :floating_ips
end

ruby-rails/app/controllers/fixed_ips_controller.rb
class FixedIpsController < ApplicationController
  before_filter :authenticate_cloud_user!
  around_filter :catch_not_found

  # GET /fixed_ips
  # GET /fixed_ips.json
  def index
    @fixed_ips = FixedIp.fixed_active

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fixed_ips }
    end
  end

  # GET /fixed_ips
  # GET /fixed_ips.json
  def unassigned
    @fixed_ips = FixedIp.fixed_inactive

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fixed_ips }
    end
  end

  def leased
  query = "SELECT address, instances.hostname FROM fixed_ips LEFT JOIN instances ON fixed_ips.instance_id = instances.id WHERE instances.created_at > (NOW() - INTERVAL 1 DAY);"
  @hash = Nova.connection.select_all(query)
  if @hash.blank? 
    redirect_to :back, :notice => "No fixed IPs have been recently leased."
  end
  end

  def released
  query = "SELECT address, instances.hostname FROM fixed_ips LEFT JOIN instances ON fixed_ips.instance_id = instances.id WHERE instances.deleted_at > (NOW() - INTERVAL 1 DAY);"
  @hash = Nova.connection.select_all(query)
  if @hash.blank?
    redirect_to :back, :notice => "No fixed IPs have been recently released."
  end
  end

  # GET /fixed_ips/1
  # GET /fixed_ips/1.json
  def show
    @fixed_ip = FixedIp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fixed_ip }
    end
  end

  # GET /fixed_ips/new
  # GET /fixed_ips/new.json
  def new
    @fixed_ip = FixedIp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fixed_ip }
    end
  end

  # GET /fixed_ips/1/edit
  def edit
    @fixed_ip = FixedIp.find(params[:id])
  end

  # POST /fixed_ips
  # POST /fixed_ips.json
  def create
    @fixed_ip = FixedIp.new(params[:fixed_ip])

    respond_to do |format|
      if @fixed_ip.save
        format.html { redirect_to @fixed_ip, notice: 'Fixed ip was successfully created.' }
        format.json { render json: @fixed_ip, status: :created, location: @fixed_ip }
      else
        format.html { render action: "new" }
        format.json { render json: @fixed_ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fixed_ips/1
  # PUT /fixed_ips/1.json
  def update
    @fixed_ip = FixedIp.find(params[:id])

    respond_to do |format|
      if @fixed_ip.update_attributes(params[:fixed_ip])
        format.html { redirect_to @fixed_ip, notice: 'Fixed ip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fixed_ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixed_ips/1
  # DELETE /fixed_ips/1.json
  def destroy
    @fixed_ip = FixedIp.find(params[:id])
    @fixed_ip.destroy

    respond_to do |format|
      format.html { redirect_to fixed_ips_url }
      format.json { head :no_content }
    end
  end
end

ruby-rails/app/helpers/fixed_ips_helper.rb
module FixedIpsHelper
end

ruby-rails/app/views/fixed_ips/_default.html.erb
<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <th>Address</th>
    <th>Network</th>
    <th>Instance</th>
    <th>Allocated</th>
    <th>Leased</th>
    <th>Reserved</th>
    <th>Virtual interface</th>
    <th>Host</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Deleted at</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fixed_ips.each do |fixed_ip| %>
  <tr>
    <td><%= fixed_ip.id %></td>
    <td><%= fixed_ip.address %></td>
    <td><%= fixed_ip.network_id %></td>
    <td><%= fixed_ip.instance_id %></td>
    <td><%= fixed_ip.allocated %></td>
    <td><%= fixed_ip.leased %></td>
    <td><%= fixed_ip.reserved %></td>
    <td><%= fixed_ip.virtual_interface_id %></td>
    <td><%= fixed_ip.host %></td>
    <td><%= fixed_ip.created_at %></td>
    <td><%= fixed_ip.updated_at %></td>
    <td><%= fixed_ip.deleted_at %></td>
    <td><%= fixed_ip.deleted %></td>
    <td><%= link_to 'Show', fixed_ip %></td>
    <td><%= link_to 'Edit', edit_fixed_ip_path(fixed_ip) %></td>
    <td><%= link_to 'Destroy', fixed_ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fixed ip', new_fixed_ip_path %>

ruby-rails/app/views/fixed_ips/_form.html.erb
<%= form_for(@fixed_ip) do |f| %>
  <% if @fixed_ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fixed_ip.errors.count, "error") %> prohibited this fixed_ip from being saved:</h2>

      <ul>
      <% @fixed_ip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :network_id %><br />
    <%= f.number_field :network_id %>
  </div>
  <div class="field">
    <%= f.label :instance_id %><br />
    <%= f.number_field :instance_id %>
  </div>
  <div class="field">
    <%= f.label :allocated %><br />
    <%= f.check_box :allocated %>
  </div>
  <div class="field">
    <%= f.label :leased %><br />
    <%= f.check_box :leased %>
  </div>
  <div class="field">
    <%= f.label :reserved %><br />
    <%= f.check_box :reserved %>
  </div>
  <div class="field">
    <%= f.label :virtual_interface_id %><br />
    <%= f.number_field :virtual_interface_id %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby-rails/app/views/fixed_ips/_leased.html.erb
<table class="table table-bordered">
  <tr>
    <th>Address</th>
    <th>Hostname</th>
  </tr>
  <% @hash.each do |key, value| %>
  <tr>
    <td><%= key["address"] %></td>
    <td><%= key["hostname"] %></td>
  </tr>
<% end %>

</table>

<br />

ruby-rails/app/views/fixed_ips/edit.html.erb
<h1>Editing fixed_ip</h1>

<%= render 'form' %>

<%= link_to 'Show', @fixed_ip %> |
<%= link_to 'Back', fixed_ips_path %>

ruby-rails/app/views/fixed_ips/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag 'dashboard-base.css.scss' -%>
<% end %>


<%= content_tag :div, :class => "dashboard" do -%>

    <%= image_tag("keys.jpg", :alt=>"")%>
        <%= content_tag :div, :class => "container" do -%>
        <%= content_tag :div, :class => "dashboard-caption" do -%>
        <h1> Fixed IPs </h1>
        <% end %>
        <% end %>
    <% end %>


<%= content_tag :div, :class => "container-fluid" do -%>
<%= content_tag :div, :class => "row-fluid" do -%>

<%= content_tag :div, :class => "span2" do -%>

<%= button_to "Networks", networks_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Fixed IPs", fixed_ips_path, :method => "get", :class => "btn btn-primary disabled"%>
<%= button_to "Latest Leased", leased_fixed_ips_path, :method => "get", :class => "btn btn-info"%>
<%= button_to "Latest Released", released_fixed_ips_path, :method => "get", :class => "btn btn-info"%>
<%= button_to "Unassigned", unassigned_fixed_ips_path, :method => "get", :class => "btn btn-info"%>
<%= button_to "Floating IPs", floating_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Virtual Interfaces", virtual_interfaces_path, :method => "get", :class => "btn btn-primary"%>

<% end %>

<%= content_tag :div, :id =>"view", :class => "span10" do -%>

<%= render 'fixed_ips/default' %>

<% end %>
<% end %>
<% end %>

ruby-rails/app/views/fixed_ips/leased.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag 'dashboard-base.css.scss' -%>
<% end %>


<%= content_tag :div, :class => "dashboard" do -%>

    <%= image_tag("keys.jpg", :alt=>"")%>
        <%= content_tag :div, :class => "container" do -%>
        <%= content_tag :div, :class => "dashboard-caption" do -%>
        <h1> Recently Leased Fixed IPs </h1>
        <% end %>
        <% end %>
    <% end %>


<%= content_tag :div, :class => "container-fluid" do -%>
<%= content_tag :div, :class => "row-fluid" do -%>

<%= content_tag :div, :class => "span2" do -%>

<%= button_to "Networks", networks_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Fixed IPs", fixed_ips_path, :method => "get", :class => "btn btn-primary disabled"%>
<%= button_to "Floating IPs", floating_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Virtual Interfaces", virtual_interfaces_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Unassigned", unassigned_fixed_ips_path, :method => "get", :class => "btn btn-info"%>

<% end %>

<%= content_tag :div, :id =>"view", :class => "span10" do -%>

<%= render 'fixed_ips/leased' %>

<% end %>
<% end %>
<% end %>

ruby-rails/app/views/fixed_ips/new.html.erb
<h1>New fixed_ip</h1>

<%= render 'form' %>

<%= link_to 'Back', fixed_ips_path %>

ruby-rails/app/views/fixed_ips/released.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag 'dashboard-base.css.scss' -%>
<% end %>


<%= content_tag :div, :class => "dashboard" do -%>

    <%= image_tag("keys.jpg", :alt=>"")%>
        <%= content_tag :div, :class => "container" do -%>
        <%= content_tag :div, :class => "dashboard-caption" do -%>
        <h1> Recently Released Fixed IPs </h1>
        <% end %>
        <% end %>
    <% end %>


<%= content_tag :div, :class => "container-fluid" do -%>
<%= content_tag :div, :class => "row-fluid" do -%>

<%= content_tag :div, :class => "span2" do -%>

<%= button_to "Networks", networks_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Fixed IPs", fixed_ips_path, :method => "get", :class => "btn btn-primary disabled"%>
<%= button_to "Floating IPs", floating_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Virtual Interfaces", virtual_interfaces_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Unassigned", unassigned_fixed_ips_path, :method => "get", :class => "btn btn-info"%>

<% end %>

<%= content_tag :div, :id =>"view", :class => "span10" do -%>

<%= render 'fixed_ips/leased' %>

<% end %>
<% end %>
<% end %>

ruby-rails/app/views/fixed_ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Created at:</b>
  <%= @fixed_ip.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @fixed_ip.updated_at %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @fixed_ip.deleted_at %>
</p>

<p>
  <b>Deleted:</b>
  <%= @fixed_ip.deleted %>
</p>

<p>
  <b>Address:</b>
  <%= @fixed_ip.address %>
</p>

<p>
  <b>Network:</b>
  <%= @fixed_ip.network_id %>
</p>

<p>
  <b>Instance:</b>
  <%= @fixed_ip.instance_id %>
</p>

<p>
  <b>Allocated:</b>
  <%= @fixed_ip.allocated %>
</p>

<p>
  <b>Leased:</b>
  <%= @fixed_ip.leased %>
</p>

<p>
  <b>Reserved:</b>
  <%= @fixed_ip.reserved %>
</p>

<p>
  <b>Virtual interface:</b>
  <%= @fixed_ip.virtual_interface_id %>
</p>

<p>
  <b>Host:</b>
  <%= @fixed_ip.host %>
</p>


<%= link_to 'Edit', edit_fixed_ip_path(@fixed_ip) %> |
<%= link_to 'Back', fixed_ips_path %>

ruby-rails/app/views/fixed_ips/unassigned.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag 'dashboard-base.css.scss' -%>
<% end %>


<%= content_tag :div, :class => "dashboard" do -%>

    <%= image_tag("keys.jpg", :alt=>"")%>
        <%= content_tag :div, :class => "container" do -%>
        <%= content_tag :div, :class => "dashboard-caption" do -%>
        <h1> Fixed IPs </h1>
        <% end %>
        <% end %>
    <% end %>


<%= content_tag :div, :class => "container-fluid" do -%>
<%= content_tag :div, :class => "row-fluid" do -%>

<%= content_tag :div, :class => "span2" do -%>

<%= button_to "Networks", networks_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Fixed IPs", fixed_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Floating IPs", floating_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Virtual Interfaces", virtual_interfaces_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Unassigned", unassigned_fixed_ips_path, :method => "get", :class => "btn btn-info disabled"%>

<% end %>

<%= content_tag :div, :id =>"view", :class => "span10" do -%>

<%= render 'layouts/hash' %>

<% end %>
<% end %>
<% end %>