ruby-rails/config/routes.rb
Cloud::Application.routes.draw do


  get "home/index"


  get "dashboard/index"


  devise_for :cloud_users

  
  resources :cloud_user do 
    put 'upgrade', :on => :member
    put 'downgrade', :on => :member
    get 'history', :on => :member
  end
  

  resources :instances do
    get 'history', :on => :collection
    get 'recent', :on => :collection
  end

  resources :virtual_interface_cloud_user_associations 


  resources :user_cloud_user_associations


  resources :user_project_associations


  resources :user_role_associations


  resources :user_project_role_associations


  resources :security_group_instance_associations 


  resources :projects


  resources :users


  resource :user_project_associations


  resources :virtual_interfaces 


  resources :snapshots


  resources :services


  resources :security_groups


  resources :security_group_rules


  resources :s3_images


  resources :networks


  resources :key_pairs


  resources :instance_types


  resources :instance_info_caches


  resources :floating_ips do
    get 'unassigned', :on => :collection
    get 'autoassigned', :on => :collection
  end


  resources :fixed_ips do
    get 'unassigned', :on => :collection
    get 'leased', :on => :collection
    get 'released', :on => :collection
  end


  resources :compute_nodes


  resources :certificates


  resources :image_properties

  
  root :to => 'home#index'


end

ruby-rails/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(cloud_user)
    cloud_user ||= CloudUser.new 
    if cloud_user.admin?
      can :manage, :all
    else
      cannot :read [User, KeyPair, SecurityGroupRules, CloudUser]
    end
  end
end

ruby-rails/app/models/certificate.rb
class Certificate < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :file_name, :project_id, :updated_at, :user_id

  belongs_to :project

end

ruby-rails/app/models/cloud_user.rb
class CloudUser < App
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, 
  :username, :sign_in_count, :current_sign_in, :last_sign_in, 
  :current_sign_in_ip, :last_sign_in_ip, :admin, :created_at, :updated_at

  has_many :virtual_interface_cloud_user_associations
  has_many_elsewhere :virtual_interfaces, :through => :virtual_interface_cloud_user_association
  has_many_elsewhere :fixed_ips, :through => :virtual_interfaces
  has_many_elsewhere :floating_ips, :through => :fixed_ips
  has_many :user_cloud_user_associations

end

ruby-rails/app/models/compute_node.rb
class ComputeNode < Nova
  attr_accessible :cpu_info, :created_at, :current_workload, :deleted, :deleted_at, :disk_available_least, :free_disk_gb, :free_ram_mb, :hypervisor_hostname, :hypervisor_type, :hypervisor_version, :local_gb, :local_gb_used, :memory_mb, :memory_mb_used, :running_vms, :service_id, :updated_at, :vcpus, :vcpus_used

  belongs_to :network
  has_many :services
end

ruby-rails/app/models/fixed_ip.rb
class FixedIp < Nova
  attr_accessible :address, :allocated, :created_at, :deleted, :deleted_at, :host, :instance_id, :leased, :network_id, :reserved, :updated_at, :virtual_interface_id

  scope :fixed_active, where("allocated=?", 1)
  scope :fixed_inactive, where("allocated=?", 0)

  has_one :virtual_interface
  has_many :floating_ips
end

ruby-rails/app/models/floating_ip.rb
class FloatingIp < Nova
  self.table_name = 'nova.floating_ips'

  attr_accessible :address, :auto_assigned, :created_at, :deleted, :deleted_at, :fixed_ip_id, :host, :interface, :pool, :project_id, :updated_at

  alias_attribute :shared_ip, :address

  scope :floating_active, where(self.arel_table[:fixed_ip_id].not_eq(nil))
  scope :floating_inactive, where(self.arel_table[:fixed_ip_id].eq(nil))
  scope :shared, floating_active.select('address, fixed_ip_id')

  has_one :fixed_ip
end

ruby-rails/app/models/image_property.rb
class ImageProperty < Glance
  attr_accessible :created_at, :deleted, :deleted_at, :image_id, :name, :updated_at, :value

  belongs_to :s3_image
end

ruby-rails/app/models/instance.rb
class Instance < Nova
  attr_accessible :access_ip_v4, :access_ip_v6, :architecture, :auto_disk_config, :availability_zone, :cell_name, :config_drive, :created_at, :default_ephemeral_device, :default_swap_device, :deleted, :deleted_at, :disable_terminate, :display_description, :display_name, :ephemeral_gb, :host, :hostname, :image_ref, :instance_type_id, :internal_id, :kernel_id, :key_data, :key_name, :launch_index, :launched_at, :launched_on, :locked, :memory_mb, :os_type, :power_state, :progress, :project_id, :ramdisk_id, :reservation_id, :root_device_name, :root_gb, :scheduled_at, :server_name, :shutdown_terminate, :task_state, :terminated_at, :updated_at, :user_data, :user_id, :uuid, :vcpus, :vm_mode, :vm_state

  scope :instances_active, where("vm_state =? OR vm_state =? AND deleted=?", "active", "building", 0)
  scope :instances_active_id, instances_active.select('id')

  has_many :security_group_instance_associations
  has_one :instance_type
  has_one :instance_info_cach

end

ruby-rails/app/models/instance_type.rb
class InstanceType < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :ephemeral_gb, :flavorid, :memory_mb, :name, :root_gb, :rxtx_factor, :swap, :updated_at, :vcpu_weight, :vcpus

  belongs_to :instance
end

ruby-rails/app/models/key_pair.rb
class KeyPair < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :fingerprint, :name, :public_key, :updated_at, :user_id

  belongs_to :user
end

ruby-rails/app/models/network.rb
class Network < Nova
  attr_accessible :bridge, :bridge_interface, :broadcast, :cidr, :cidr_v6, :created_at, :deleted, :deleted_at, :dhcp_start, :dns1, :dns2, :gateway, :gateway_v6, :host, :injected, :label, :multi_host, :netmask, :netmask_v6, :priority, :project_id, :rxtx_base, :updated_at, :uuid, :vlan, :vpn_private_address, :vpn_public_address, :vpn_public_port

  has_many :security_group_instance_associations
  has_many :compute_nodes

end

ruby-rails/app/models/project.rb
class Project < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :description, :name, :project_manager, :updated_at

  has_many :user_project_associations
  has_one :certificate
end

ruby-rails/app/models/s3_image.rb
class S3Image < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :updated_at, :uuid

  has_one :image_property
end

ruby-rails/app/models/security_group.rb
class SecurityGroup < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :description, :name, :project_id, :updated_at, :user_id

  has_many :security_group_instance_associations
  has_many :user_role_associations
  has_many :security_group_rules

end

ruby-rails/app/models/service.rb
class Service < Nova
  attr_accessible :availability_zone, :binary, :created_at, :deleted, :deleted_at, :disabled, :host, :report_count, :topic, :updated_at
  
  belongs_to :compute_node
  
  has_many :virtual_interfaces
end

ruby-rails/app/models/snapshot.rb
class Snapshot < Nova
  attr_accessible :created_at, :deleted, :deleted_at, :display_description, :display_name, :progress, :project_id, :scheduled_at, :status, :updated_at, :user_id, :volume_id, :volume_size

  has_one :image_property

end

ruby-rails/app/models/user.rb
class User < Nova
  attr_accessible :access_key, :created_at, :deleted, :deleted_at, :is_admin, :name, :secret_key, :updated_at

  has_many :user_project_associations
  has_many :user_role_associations

end

ruby-rails/app/helpers/admin_helper.rb
module AdminHelper
end

ruby-rails/app/helpers/home_helper.rb
module HomeHelper
end

ruby-rails/app/helpers/users_helper.rb
module UsersHelper
end

ruby-rails/app/views/layouts/_footer.html.erb
      <!-- FOOTER -->
      <footer>
        <p class="pull-right">
        <%= render 'devise/shared/links' %>
        </p>
        <p>&copy; Jordan Blocher and Nick King&middot; <a href="http://www.unr.edu">UNR</a></p>
      </footer>

    </div><!-- /.container -->

ruby-rails/app/views/layouts/_hash.html.erb
<table class="table table-bordered">
  <tr>
    <th>Display Name</th>
    <th>Created At</th>
  </tr>
  <% @hash.each do |key, value| %>
  <tr>
    <td><%= key["display_name"] %></td>
    <td><%= key["created_at"] %></td>
  </tr>
<% end %>

</table>

<br />

ruby-rails/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

ruby-rails/app/views/layouts/_navbar.html.erb
   
   
    <!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">

        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/dashboard/index">Cloud Admin</a>
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="active"><a href="/home/index">Home</a></li>
                <!-- Read about Bootstrap dropdowns at http://twitter.github.com/bootstrap/javascript.html#dropdowns -->
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cloud Instances<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Project</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Instances</li>
                    <li><a href="#">Instance</a></li>
                  </ul>
                </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->

      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->
    

ruby-rails/app/views/layouts/_navigation.html.erb
<%= link_to "Cloud", root_path, :class => 'brand' %>
<ul class="nav">
  <% if cloud_user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_cloud_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_cloud_user_session_path %>
    </li>
  <% end %>
  <% if cloud_user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_cloud_user_registration_path %>
    </li>
    <% if current_cloud_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', cloud_users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_cloud_user_registration_path %>
    </li>
  <% end %>
</ul>

ruby-rails/app/views/layouts/_rel.html.erb
        <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
      <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
      <link rel="shortcut icon" href="/assets/ico/favicon.png">

ruby-rails/app/views/layouts/_shim.html.erb
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

ruby-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Cloud</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
                                   
<%= render 'layouts/shim' %>   
<%= render 'layouts/rel' %>   

<%= yield :head %>
 </head>

  <!-- START_HIGHLIGHT -->
<body class='<%= controller.controller_name %>'>
<!-- END_HIGHLIGHT -->           

 <%= render 'layouts/navbar' %>    
<br/><br/><br/><br/>

<%= yield %>

<%if flash[:notice]%>
<p class="notice"><%= notice %></p>
<%end%>

<%if flash[:alert]%>
<p class="alert"><%= alert %></p>
<%end%>

 <%= render 'layouts/footer' %>


</body>
</html>