ruby-rails/config/routes.rb
Cloud::Application.routes.draw do


  get "home/index"


  get "dashboard/index"


  devise_for :cloud_users

  
  resources :cloud_user do 
    put 'upgrade', :on => :member
    put 'downgrade', :on => :member
    get 'history', :on => :member
  end
  

  resources :instances do
    get 'history', :on => :collection
    get 'recent', :on => :collection
  end

  resources :virtual_interface_cloud_user_associations 


  resources :user_cloud_user_associations


  resources :user_project_associations


  resources :user_role_associations


  resources :user_project_role_associations


  resources :security_group_instance_associations 


  resources :projects


  resources :users


  resource :user_project_associations


  resources :virtual_interfaces 


  resources :snapshots


  resources :services


  resources :security_groups


  resources :security_group_rules


  resources :s3_images


  resources :networks


  resources :key_pairs


  resources :instance_types


  resources :instance_info_caches


  resources :floating_ips do
    get 'unassigned', :on => :collection
    get 'autoassigned', :on => :collection
  end


  resources :fixed_ips do
    get 'unassigned', :on => :collection
    get 'leased', :on => :collection
    get 'released', :on => :collection
  end


  resources :compute_nodes


  resources :certificates


  resources :image_properties

  
  root :to => 'home#index'


end

ruby-rails/app/controllers/instance_types_controller.rb
class InstanceTypesController < ApplicationController
  before_filter :authenticate_cloud_user!
  
  # GET /instance_types
  # GET /instance_types.json
  def index
    @instance_types = InstanceType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instance_types }
    end
  end

  # GET /instance_types/1
  # GET /instance_types/1.json
  def show
    @instance_type = InstanceType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instance_type }
    end
  end

  # GET /instance_types/new
  # GET /instance_types/new.json
  def new
    @instance_type = InstanceType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instance_type }
    end
  end

  # GET /instance_types/1/edit
  def edit
    @instance_type = InstanceType.find(params[:id])
  end

  # POST /instance_types
  # POST /instance_types.json
  def create
    @instance_type = InstanceType.new(params[:instance_type])

    respond_to do |format|
      if @instance_type.save
        format.html { redirect_to @instance_type, notice: 'Instance type was successfully created.' }
        format.json { render json: @instance_type, status: :created, location: @instance_type }
      else
        format.html { render action: "new" }
        format.json { render json: @instance_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instance_types/1
  # PUT /instance_types/1.json
  def update
    @instance_type = InstanceType.find(params[:id])

    respond_to do |format|
      if @instance_type.update_attributes(params[:instance_type])
        format.html { redirect_to @instance_type, notice: 'Instance type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instance_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instance_types/1
  # DELETE /instance_types/1.json
  def destroy
    @instance_type = InstanceType.find(params[:id])
    @instance_type.destroy

    respond_to do |format|
      format.html { redirect_to instance_types_url }
      format.json { head :no_content }
    end
  end
end

ruby-rails/app/helpers/instance_types_helper.rb
module InstanceTypesHelper
end

ruby-rails/app/views/instance_types/_default.html.erb
<table class="table table-bordered">
  <tr>
   <th>Name</th>
    <th>Memory mb</th>
    <th>Vcpus</th>
    <th>Swap</th>
    <th>Vcpu weight</th>
    <th>Flavorid</th>
    <th>Rxtx factor</th>
    <th>Root gb</th>
    <th>Ephemeral gb</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Deleted at</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instance_types.each do |instance_type| %>
  <tr>
   <td><%= instance_type.name %></td>
    <td><%= instance_type.memory_mb %></td>
    <td><%= instance_type.vcpus %></td>
    <td><%= instance_type.swap %></td>
    <td><%= instance_type.vcpu_weight %></td>
    <td><%= instance_type.flavorid %></td>
    <td><%= instance_type.rxtx_factor %></td>
    <td><%= instance_type.root_gb %></td>
    <td><%= instance_type.ephemeral_gb %></td>
    <td><%= instance_type.created_at %></td>
    <td><%= instance_type.updated_at %></td>
    <td><%= instance_type.deleted_at %></td>
    <td><%= instance_type.deleted %></td>
    <td><%= link_to 'Show', instance_type %></td>
    <td><%= link_to 'Edit', edit_instance_type_path(instance_type) %></td>
    <td><%= link_to 'Destroy', instance_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instance type', new_instance_type_path %>

ruby-rails/app/views/instance_types/_form.html.erb
<%= form_for(@instance_type) do |f| %>
  <% if @instance_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance_type.errors.count, "error") %> prohibited this instance_type from being saved:</h2>

      <ul>
      <% @instance_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :memory_mb %><br />
    <%= f.number_field :memory_mb %>
  </div>
  <div class="field">
    <%= f.label :vcpus %><br />
    <%= f.number_field :vcpus %>
  </div>
  <div class="field">
    <%= f.label :swap %><br />
    <%= f.number_field :swap %>
  </div>
  <div class="field">
    <%= f.label :vcpu_weight %><br />
    <%= f.number_field :vcpu_weight %>
  </div>
  <div class="field">
    <%= f.label :flavorid %><br />
    <%= f.text_field :flavorid %>
  </div>
  <div class="field">
    <%= f.label :rxtx_factor %><br />
    <%= f.text_field :rxtx_factor %>
  </div>
  <div class="field">
    <%= f.label :root_gb %><br />
    <%= f.number_field :root_gb %>
  </div>
  <div class="field">
    <%= f.label :ephemeral_gb %><br />
    <%= f.number_field :ephemeral_gb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby-rails/app/views/instance_types/edit.html.erb
<h1>Editing instance_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance_type %> |
<%= link_to 'Back', instance_types_path %>

ruby-rails/app/views/instance_types/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag 'dashboard-base.css.scss' -%>
<% end %>


<%= content_tag :div, :class => "dashboard" do -%>

    <%= image_tag("keys.jpg", :alt=>"")%>
        <%= content_tag :div, :class => "container" do -%>
        <%= content_tag :div, :class => "dashboard-caption" do -%>
        <h1> Flavors </h1>
        <% end %>
        <% end %>
    <% end %>


<%= content_tag :div, :class => "container-fluid" do -%>
<%= content_tag :div, :class => "row-fluid" do -%>

<%= content_tag :div, :class => "span2" do -%>

<%= button_to "Instances", instances_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "History", history_instances_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Flavors", instance_types_path, :method => "get", :class => "btn btn-primary disabled"%>
<%= button_to "Cache", instance_info_caches_path, :method => "get", :class => "btn btn-primary"%>

<% end %>

<%= content_tag :div, :class => "span10" do -%>

<%= render 'instance_types/default' %>

<% end %>
<% end %>
<% end %>

ruby-rails/app/views/instance_types/new.html.erb
<h1>New instance_type</h1>

<%= render 'form' %>

<%= link_to 'Back', instance_types_path %>

ruby-rails/app/views/instance_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Created at:</b>
  <%= @instance_type.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @instance_type.updated_at %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @instance_type.deleted_at %>
</p>

<p>
  <b>Deleted:</b>
  <%= @instance_type.deleted %>
</p>

<p>
  <b>Name:</b>
  <%= @instance_type.name %>
</p>

<p>
  <b>Memory mb:</b>
  <%= @instance_type.memory_mb %>
</p>

<p>
  <b>Vcpus:</b>
  <%= @instance_type.vcpus %>
</p>

<p>
  <b>Swap:</b>
  <%= @instance_type.swap %>
</p>

<p>
  <b>Vcpu weight:</b>
  <%= @instance_type.vcpu_weight %>
</p>

<p>
  <b>Flavorid:</b>
  <%= @instance_type.flavorid %>
</p>

<p>
  <b>Rxtx factor:</b>
  <%= @instance_type.rxtx_factor %>
</p>

<p>
  <b>Root gb:</b>
  <%= @instance_type.root_gb %>
</p>

<p>
  <b>Ephemeral gb:</b>
  <%= @instance_type.ephemeral_gb %>
</p>


<%= link_to 'Edit', edit_instance_type_path(@instance_type) %> |
<%= link_to 'Back', instance_types_path %>