ruby-rails/config/routes.rb
Cloud::Application.routes.draw do


  get "home/index"


  get "dashboard/index"


  devise_for :cloud_users

  
  resources :cloud_user do 
    put 'upgrade', :on => :member
    put 'downgrade', :on => :member
    get 'history', :on => :member
  end
  

  resources :instances do
    get 'history', :on => :collection
    get 'recent', :on => :collection
  end

  resources :virtual_interface_cloud_user_associations 


  resources :user_cloud_user_associations


  resources :user_project_associations


  resources :user_role_associations


  resources :user_project_role_associations


  resources :security_group_instance_associations 


  resources :projects


  resources :users


  resource :user_project_associations


  resources :virtual_interfaces 


  resources :snapshots


  resources :services


  resources :security_groups


  resources :security_group_rules


  resources :s3_images


  resources :networks


  resources :key_pairs


  resources :instance_types


  resources :instance_info_caches


  resources :floating_ips do
    get 'unassigned', :on => :collection
    get 'autoassigned', :on => :collection
  end


  resources :fixed_ips do
    get 'unassigned', :on => :collection
    get 'leased', :on => :collection
    get 'released', :on => :collection
  end


  resources :compute_nodes


  resources :certificates


  resources :image_properties

  
  root :to => 'home#index'


end

ruby-rails/app/models/virtual_interface_cloud_user_association.rb
class VirtualInterfaceCloudUserAssociation < App
  attr_accessible :cloud_username, :created_at, :deleted_at, :shared_ip, 
  :updated_at, :virtual_interface_id

  alias_attribute  :current_sign_in_ip, :shared_ip
  alias_attribute :address, :shared_ip

  belongs_to :cloud_user
  belongs_to :virtual_interface

end

ruby-rails/app/controllers/virtual_interface_cloud_user_associations_controller.rb
class VirtualInterfaceCloudUserAssociationsController < ApplicationController
  # GET /virtual_interface_cloud_user_associations
  # GET /virtual_interface_cloud_user_associations.json
  def index
      @virtual_interface_cloud_user_associations = VirtualInterfaceCloudUserAssociation.all
    respond_to do |format|
      format.html 
      format.json { render json: @virtual_interface_cloud_user_association }
    end
  end

  # GET /virtual_interface_cloud_user_associations/1
  # GET /virtual_interface_cloud_user_associations/1.json
  def show
    @virtual_interface_cloud_user_association = VirtualInterfaceCloudUserAssociation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @virtual_interface_cloud_user_association }
    end
  end

  # GET /virtual_interface_cloud_user_associations/new
  # GET /virtual_interface_cloud_user_associations/new.json
  def new
    if App.connection.table_exists? 'virtual_interface_cloud_user_associations'
      App.connection.execute('DROP TABLE virtual_interface_cloud_user_associations')
    end
    App.connection.create_table('virtual_interface_cloud_user_associations') do |t|
        t.column :created_at, :datetime
        t.column :deleted_at, :datetime
        t.column :updated_at, :datetime
        t.column :shared_ip, :string
        t.column :cloud_username, :string
        t.column :virtual_interface_id, :integer
    end
    floating_shared = FloatingIp.shared
    CloudUser.all.each do |cshared|
      @shared = VirtualInterfaceCloudUserAssociation.new
      FloatingIp.shared.each do |fshared|
        if cshared.current_sign_in_ip == fshared.address
          shared_interface_id = FixedIp.fixed_active.select('virtual_interface_id').where('id=?',fshared.fixed_ip_id)
          @shared.update_attributes(:cloud_username => cshared.username, :shared_ip => cshared.current_sign_in_ip, :virtual_interface_id => shared_interface_id)
        end
      end
      @shared.save
    end
    redirect_to '/virtual_interface_cloud_user_associations'
  end

end

ruby-rails/app/helpers/virtual_interface_cloud_user_associations_helper.rb
module VirtualInterfaceCloudUserAssociationsHelper
end

ruby-rails/app/views/virtual_interface_cloud_user_associations/_default.html.erb
<table class="table table-bordered">
  <tr>
    <th>Shared IP</th>
    <th>Cloud User</th>
    <th>Virtual Interface ID</th>
  </tr>

<% @virtual_interface_cloud_user_associations.each do |virtual_interface_cloud_user_association| %>
  <tr>
    <td><%= virtual_interface_cloud_user_association.shared_ip %></td>
    <td><%= virtual_interface_cloud_user_association.cloud_username %></td>
    <td><%= virtual_interface_cloud_user_association.virtual_interface_id %></td>
  </tr>
<% end %>
</table>

<br />

ruby-rails/app/views/virtual_interface_cloud_user_associations/_form.html.erb
<%= form_for(@virtual_interface_cloud_user_association) do |f| %>
  <% if @virtual_interface_cloud_user_association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@virtual_interface_cloud_user_association.errors.count, "error") %> prohibited this virtual_interface_cloud_user_association from being saved:</h2>

      <ul>
      <% @virtual_interface_cloud_user_association.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :cloud_username %><br />
    <%= f.text_field :cloud_username %>
  </div>
  <div class="field">
    <%= f.label :virtual_interface_id %><br />
    <%= f.number_field :virtual_interface_id %>
  </div>
  <div class="field">
    <%= f.label :shared_ip %><br />
    <%= f.text_field :shared_ip %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby-rails/app/views/virtual_interface_cloud_user_associations/edit.html.erb
<h1>Editing virtual_interface_cloud_user_association</h1>

<%= render 'form' %>

<%= link_to 'Show', @virtual_interface_cloud_user_association %> |
<%= link_to 'Back', virtual_interface_cloud_user_associations_path %>

ruby-rails/app/views/virtual_interface_cloud_user_associations/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag 'dashboard-base.css.scss' -%>
<% end %>


<%= content_tag :div, :class => "dashboard" do -%>

    <%= image_tag("keys.jpg", :alt=>"")%>
        <%= content_tag :div, :class => "container" do -%>
        <%= content_tag :div, :class => "dashboard-caption" do -%>
        <h1> Current Shared IPs </h1>
        <% end %>
        <% end %>
    <% end %>


<%= content_tag :div, :class => "container-fluid" do -%>
<%= content_tag :div, :class => "row-fluid" do -%>

<%= content_tag :div, :class => "span2" do -%>

<%= button_to "Networks", networks_path, :method => "get", :class => "btn btn-primary disabled"%>
<%= button_to "Fixed IPs", fixed_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Floating IPs", floating_ips_path, :method => "get", :class => "btn btn-primary"%>
<%= button_to "Virtual Interfaces", virtual_interfaces_path, :method => "get", :class => "btn btn-primary"%>

<% end %>

<%= content_tag :div, :id =>"view", :class => "span10" do -%>

<%= render 'virtual_interface_cloud_user_associations/default' %>

<% end %>
<% end %>
<% end %>

ruby-rails/app/views/virtual_interface_cloud_user_associations/new.html.erb
<h1>New virtual_interface_cloud_user_association</h1>

<%= render 'form' %>

<%= link_to 'Back', virtual_interface_cloud_user_associations_path %>

ruby-rails/app/views/virtual_interface_cloud_user_associations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Created at:</b>
  <%= @virtual_interface_cloud_user_association.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @virtual_interface_cloud_user_association.updated_at %>
</p>

<p>
  <b>Cloud username:</b>
  <%= @virtual_interface_cloud_user_association.cloud_username %>
</p>

<p>
  <b>Virtual interface:</b>
  <%= @virtual_interface_cloud_user_association.virtual_interface_id %>
</p>

<p>
  <b>Shared ip:</b>
  <%= @virtual_interface_cloud_user_association.shared_ip %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @virtual_interface_cloud_user_association.deleted_at %>
</p>


<%= link_to 'Edit', edit_virtual_interface_cloud_user_association_path(@virtual_interface_cloud_user_association) %> |
<%= link_to 'Back', virtual_interface_cloud_user_associations_path %>